const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const harness=fs.readFileSync(path.join(__dirname,'campaign.cjs'),'utf8').split('const g=game();')[0];
const game=new Function('require','__dirname',harness+'\nreturn game;')(require,__dirname);
const g=game(),r=g.run;
r("resetCloth(350);keys.add('arrowup');for(let i=0;i<120;i++)clothStep();keys.clear()");
const limited=r('groundAt(center())-cloth.reduce((n,p)=>n+p.y,0)/cloth.length');
assert.ok(limited>20&&limited<220,'up arrow lifts cloth before the permit');
r("discoveries.add('puzzle:air');resetCloth(350);keys.add('arrowup');for(let i=0;i<180;i++)clothStep();keys.clear()");
const altitude=r('groundAt(center())-cloth.reduce((n,p)=>n+p.y,0)/cloth.length');
assert.ok(altitude>300&&altitude<540,'permit unlocks sustained bounded flight');
r("keys.add('arrowright');for(let i=0;i<45;i++)clothStep();keys.clear()");
assert.ok(r('center()')>380,'cloth steers while airborne');
const high=r('cloth.reduce((n,p)=>n+p.y,0)/cloth.length');
r('for(let i=0;i<100;i++)clothStep()');
assert.ok(r('cloth.reduce((n,p)=>n+p.y,0)/cloth.length')>high,'release drifts down');
r("saveGame()");const restored=game(Object.fromEntries(g.store));assert.equal(restored.run('canFloat()'),true,'permit survives reload');
const fan=game();fan.run("travel('attic',850);resetCloth(850);for(let i=0;i<130;i++)clothStep()");
assert.ok(fan.run('groundAt(center())-cloth.reduce((n,p)=>n+p.y,0)/cloth.length')>100,'fan lifts cloth without the permit');
assert.ok(fan.run("objects.filter(o=>o.device==='breeze').length")>=2);
const c=game();c.run("travel('attic');renderRoomCompletion(roomObjectiveStatus())");assert.ok(c.nodes.get('#room-complete').classList.contains('hidden'),'unfinished room has no completion overlay');
c.run("discoveries.add('puzzle:kite');discoveries.add('puzzle:air');renderRoomCompletion(roomObjectiveStatus())");assert.equal(c.nodes.get('#room-complete').classList.contains('hidden'),false);assert.equal(c.run("discoveries.has('room-complete:v1:attic')"),true);
c.run('time+=5;renderRoomCompletion(roomObjectiveStatus())');assert.ok(c.nodes.get('#room-complete').classList.contains('hidden'),'overlay expires without repeating');
c.run("travel('hub');renderRoomCompletion(roomObjectiveStatus())");assert.ok(c.nodes.get('#room-complete').classList.contains('hidden'),'passages do not falsely complete');
c.run('soundOn=true;toggleGameSound()');assert.equal(c.store.get('rag-meg-sound-v1'),'off');assert.equal(c.nodes.get('#quick-sound').textContent,'SOUND OFF');assert.equal(c.nodes.get('#sound').textContent,'SOUND — off');
console.log('PASS: up-arrow lift, unlocked flight, steering, descent, saved permit, fans, room completion once, passages, synchronized saved sound preference.');
